import { ArrowLeft, ChevronDown, Edit3, MoreHorizontal, Plus, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { products } from "../lib/mockServices";

type Props = { setLocation: (path: string) => void };
export function AdminProductsPage({ setLocation }: Props) {
  return <div className="admin-shell"><AdminSide setLocation={setLocation} active="Products" /><main className="admin-main"><header className="admin-header"><div><p className="eyebrow">CATALOG / INVENTORY</p><h1>PRODUCTS</h1></div><button className="button button-light" onClick={() => toast.success("Product editor opened")}>ADD PRODUCT <Plus size={16} /></button></header><div className="admin-content"><div className="admin-toolbar"><div className="admin-search"><Search size={16} /><input placeholder="Search products" /></div><button onClick={() => toast("Filters coming soon")}><span>ALL CATEGORIES</span><ChevronDown size={15} /></button><button onClick={() => toast("Sort options coming soon")}><span>NEWEST FIRST</span><ChevronDown size={15} /></button></div><section className="admin-card catalog-table"><div className="admin-table"><div className="admin-table-row admin-table-head"><span>PRODUCT</span><span>CATEGORY</span><span>PRICE</span><span>STOCK</span><span>STATUS</span><span>ACTIONS</span></div>{products.map((p) => <div className="admin-table-row" key={p.id}><span className="product-cell"><img src={p.image} alt={p.alt} /><strong>{p.name}</strong></span><span>{p.category}</span><span>${p.price.toFixed(2)}</span><span>{p.inStock ? Math.floor(24 + p.price / 3) : 0}</span><span className={`status ${p.inStock ? "delivered" : "cancelled"}`}>{p.inStock ? "In stock" : "Out of stock"}</span><span className="table-actions"><button aria-label={`Edit ${p.name}`} onClick={() => toast.success("Product editor opened", { description: p.name })}><Edit3 size={15} /></button><button aria-label={`Delete ${p.name}`} onClick={() => toast("Delete requires confirmation in the API") }><Trash2 size={15} /></button><button aria-label="More actions" onClick={() => toast("More actions coming soon")}><MoreHorizontal size={15} /></button></span></div>)}</div></section></div></main></div>;
}

export function AdminSide({ setLocation, active }: Props & { active: string }) { return <aside className="admin-sidebar"><button className="admin-brand" onClick={() => setLocation("/")}>AVIRO<span>.</span><small>STUDIO / ADMIN</small></button><nav><p>OVERVIEW</p><button className={active === "Dashboard" ? "active" : ""} onClick={() => setLocation("/admin")}><span className="admin-icon">⌁</span> Dashboard</button><p>CATALOG</p><button className={active === "Products" ? "active" : ""} onClick={() => setLocation("/admin/products")}><Plus size={16} /> Products</button><button onClick={() => toast("Category manager coming soon")}><span className="admin-icon">▦</span> Categories</button><p>OPERATIONS</p><button className={active === "Orders" ? "active" : ""} onClick={() => setLocation("/admin/orders")}><span className="admin-icon">□</span> Orders <span className="admin-nav-count">12</span></button><button onClick={() => toast("Customer directory coming soon")}><span className="admin-icon">○</span> Customers</button></nav><button className="back-to-store" onClick={() => setLocation("/")}><ArrowLeft size={15} /> BACK TO STORE</button></aside>; }
